# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""
  DOCKER_BUILDKIT: 1
  USE_NEWER_NIX: 1

steps:
 # We need to sign commits that update brew formulae separately
 - label: Sign formulae update commits
   if: build.branch =~ /^auto\/update-brew-formulae-.*/
   commands:
   - nix develop .#buildkite
       --command './scripts/sign-commits.sh'
 # To avoid race-conditions for the gpg key between jobs which sometimes leads to weird errors
 - wait

 - label: Build ubuntu source packages
   key: build-ubuntu-source-packages
   commands:
   - eval "$SET_VERSION"
   - nix develop .#docker-tezos-packages -c ./docker/build/ubuntu/build.py --type source --launchpad-sources
   artifact_paths:
     - ./out/*

 - label: Build fedora source packages
   key: build-fedora-source-packages
   commands:
   - eval "$SET_VERSION"
   - nix develop .#docker-tezos-packages -c ./docker/build/fedora/build.py --type source
   artifact_paths:
     - ./out/*

 - label: Sign ubuntu source packages
   depends_on:
   - "build-ubuntu-source-packages"
   key: sign-ubuntu-source-packages
   commands:
   - eval "$SET_VERSION"
   - buildkite-agent artifact download "out/*" . --step build-ubuntu-source-packages
   - nix develop .#docker-tezos-packages -c ./docker/build/ubuntu/sign.py -d out -i 'Serokell <tezos-packaging@serokell.io>'
   artifact_paths:
     - ./out/*

 - label: Sign fedora source packages
   depends_on:
   - "build-fedora-source-packages"
   key: sign-fedora-source-packages
   commands:
   - eval "$SET_VERSION"
   - buildkite-agent artifact download "out/*" . --step build-fedora-source-packages
   - nix develop .#docker-tezos-packages -c ./docker/build/fedora/sign.py -d out -i 'Serokell <tezos-packaging@serokell.io>'
   artifact_paths:
     - ./out/*

 - label: Publish ubuntu native packages
   depends_on:
   - "sign-ubuntu-source-packages"
   commands:
   - eval "$SET_VERSION"
   - buildkite-agent artifact download "out/*" . --step sign-ubuntu-source-packages
   - nix develop .#buildkite -c ./docker/build/ubuntu/upload.py -d out

 - label: Publish fedora native packages
   depends_on:
   - "sign-fedora-source-packages"
   commands:
   - eval "$SET_VERSION"
   - buildkite-agent artifact download "out/*" . --step sign-fedora-source-packages
   - nix develop .#buildkite -c ./docker/build/fedora/upload.py -d out
