# SPDX-FileCopyrightText: 2022 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  USE_NEWER_NIX: 1
  DOCKER_BUILDKIT: 1
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""


steps:
 - label: build-via-docker
   if: build.tag == "test-736"
   key: build-via-docker
   commands:
   - eval "$SET_VERSION"
   - cd docker
   - ./docker-static-build.sh
   - buildkite-agent artifact upload /tmp/binaries.txt
   artifact_paths:
     - ./docker/octez-*
   agents:
     queue: "docker"


 - label: Update binaries list
   depends_on:
   - "build-via-docker"
  #  - "add-bigsur-hashes"
   if: build.tag == "test-736"
   key: update-binaries
   commands:
    - buildkite-agent artifact download tmp/binaries.txt docker --step "build-via-docker"
    - cd docker
    - nix develop .#autorelease -c ./update-binaries.sh
