# SPDX-FileCopyrightText: 2022 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

env:
  USE_NEWER_NIX: 1
  DOCKER_BUILDKIT: 1
  SET_VERSION: "export OCTEZ_VERSION=\"$(cat meta.json | jq -r '.tezos_ref' | cut -d'/' -f3)\""


steps:
 - label: build-via-docker
   # this step is used as a dependency, so we're defining 'key' explicitely
   key: build-via-docker
   if: build.tag == "test-695"
   commands:
   - eval "$SET_VERSION"
   - cd docker
   - ./docker-static-build.sh
   artifact_paths:
     - ./docker/octez-*
   agents:
     queue: "docker"

 - label: build-arm-via-docker
   # this step is used as a dependency, so we're defining 'key' explicitely
   key: build-arm-via-docker
   if: build.tag == "test-695"
   commands:
   - eval "$SET_VERSION"
   - cd docker
   - ./docker-static-build.sh
   - >
     for f in ./octez-*; do
       mv "\$f" "\$f-arm64"
     done
   artifact_paths:
     - ./docker/octez-*
   agents:
     queue: "arm64-darwin"

 - label: create auto release/pre-release
   key: auto-release
   if: build.tag == "test-695"
   commands:
   - mkdir binaries
   - mkdir arm-binaries
   - buildkite-agent artifact download "docker/*" binaries --step "build-via-docker"
   - buildkite-agent artifact download "docker/*" arm-binaries --step "build-arm-via-docker"
   - ls binaries
   - nix develop .#autorelease -c ./scripts/autorelease.sh "$BUILDKITE_MESSAGE"
   depends_on:
    - "build-via-docker"
    - "build-arm-via-docker"

 - label: Build Big Sur x86_64 bottles
   key: build-bottles-big-sur-x86_64
   if: build.tag == "test-695"
   depends_on:
    - "auto-release"
   agents:
     queue: "x86_64-rosetta-darwin"
   commands:
   - nix develop .#autorelease-macos -c ./scripts/build-all-bottles.sh "big_sur"
   artifact_paths:
     - '*.bottle.*'
   retry:
     automatic:
       limit: 1

 - label: Build Big Sur arm64 bottles
   key: build-bottles-big-sur-arm64
   if: build.tag == "test-695"
   depends_on:
    - "auto-release"
   agents:
     queue: "arm64-darwin"
   commands:
   - nix develop .#autorelease-macos -c ./scripts/build-all-bottles.sh "arm64_big_sur"
   artifact_paths:
     - '*.bottle.*'
   retry:
     automatic:
       limit: 1

 - label: Add Big Sur bottle hashes to formulae
   key: list-bottles
   depends_on:
   - "build-bottles-big-sur-arm64"
   - "build-bottles-big-sur-x86_64"
   if: build.tag == "test-695"
   soft_fail: true # No artifacts to download if all the bottles are already built
   commands:
   - mkdir -p "Big Sur"
   - gh release download build.tag -D "Big Sur/" -p "*.bottle.tar.gz"
   - ls "Big Sur"

 - label: delete test-release pre-release
   commands:
   - nix develop .#autorelease -c ./scripts/del-test-release.sh "$BUILDKITE_MESSAGE"
   if: build.tag == "test-695"
   depends_on:
    - "build-bottles-big-sur-x86_64"
    - "build-bottles-big-sur-arm64"
    - "list-bottles"
