#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

set -euo pipefail

# Note: the 'TEZOS_CLIENT_DIR' env var is expected and used by the rollup node

# $PROTOCOL should be defined in the system unit environment
node="/usr/bin/octez-$TYPE-rollup-node-$PROTOCOL"

"$node" init "$ROLLUP_MODE" config \
    for "$ROLLUP_ALIAS" \
    --rpc-addr "$ROLLUP_NODE_RPC_ENDPOINT" \
    --force

"$node" --endpoint "$NODE_RPC_SCHEME://$NODE_RPC_ADDR" \
    run "$ROLLUP_MODE" for "$ROLLUP_ALIAS" &
