#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2022 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

set -euo pipefail

tezos_client="/usr/bin/octez-client"

config="$DATA_DIR/config"

mkdir -p "$DATA_DIR"

"$tezos_client" --base-dir "$DATA_DIR" \
                --endpoint "$NODE_RPC_ENDPOINT" \
                config "$([[ -f $config ]] && echo "update" || echo "init")"
