#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2022 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

set -euo pipefail

if [ -z "$1" ]; then
    echo "Please call this script with the custom baking instance name."
    exit 1
fi

instance_name="$1"

if [[ -n ${RESET_ON_STOP} ]]; then
    node_data_dir="$(systemctl show tezos-node-custom@"$instance_name".service | grep -o "NODE_DATA_DIR=\S*" | cut -d'=' -f2)"
    rm -rf "$node_data_dir"
fi
