#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

set -euo pipefail

# Note: the 'TEZOS_CLIENT_DIR' env var is expected and used by the rollup node

node="/usr/bin/octez-smart-rollup-node"

"$node" init "$ROLLUP_MODE" config \
    for "$ROLLUP_ALIAS" \
    with operators \
    "$ROLLUP_OPERATORS" \
    --data-dir "$ROLLUP_DATA_DIR" \
    --force

exec "$node" --endpoint "$NODE_RPC_ENDPOINT" \
    run "$ROLLUP_MODE" for "$ROLLUP_ALIAS" \
    with operators "$ROLLUP_OPERATORS" \
    --data-dir "$ROLLUP_DATA_DIR"
