#!/usr/bin/bash

# SPDX-FileCopyrightText: 2020 TQ Tezos <https://tqtezos.com/>
#
# SPDX-License-Identifier: LicenseRef-MIT-TQ

set -euo pipefail

node="/usr/bin/tezos-node"

mkdir -p "$DATA_DIR"
if [ ! -f "$DATA_DIR/config.json" ]; then
    echo "Configuring the node..."
    "$node" config init \
            --data-dir "$DATA_DIR" \
            --rpc-addr "$NODE_RPC_ADDR" \
            --network "$NETWORK"
            "$@"
else
    echo "Updating the node configuration..."
    "$node" config update \
            --data-dir "$DATA_DIR" \
            --rpc-addr "$NODE_RPC_ADDR" \
            --network "$NETWORK"
            "$@"
fi

# Launching the node

if [[ -z "$CERT_PATH" || -z "$KEY_PATH" ]]; then
    exec "$node" run --data-dir "$DATA_DIR"
else
    exec "$node" run --data-dir "$DATA_DIR" --rpc-tls="$CERT_PATH","$KEY_PATH"
fi
