#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

set -euo pipefail

node="/usr/bin/octez-node"

if [[ ! -d "$TEZOS_NODE_DIR" ]]; then
    mkdir -p "$TEZOS_NODE_DIR"
fi

if [[ -d "$TEZOS_NODE_DIR/store" ]]; then
    "$node" upgrade --data-dir "$TEZOS_NODE_DIR" storage
    rm -rf "$TEZOS_NODE_DIR/lmdb_store_to_remove"
fi

if [[ ! -f "$TEZOS_NODE_DIR/identity.json" ]]; then
    "$node" identity generate --data-dir "$TEZOS_NODE_DIR"
fi
