#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2020 TQ Tezos <https://tqtezos.com/>
#
# SPDX-License-Identifier: LicenseRef-MIT-TQ

set -euo pipefail

# Note: the 'TEZOS_CLIENT_DIR' env var is expected and used by the accuser

# $PROTOCOL should be defined in the system unit environment
accuser="/usr/bin/octez-accuser-$PROTOCOL"

accuser_config="$TEZOS_CLIENT_DIR/config"
mkdir -p "$TEZOS_CLIENT_DIR"

if [ ! -f "$accuser_config" ]; then
    "$accuser" --endpoint "$NODE_RPC_SCHEME://$NODE_RPC_ADDR" \
               config init --output "$accuser_config" >/dev/null 2>&1
else
    "$accuser" --endpoint "$NODE_RPC_SCHEME://$NODE_RPC_ADDR" \
               config update >/dev/null 2>&1
fi

exec "$accuser" --endpoint "$NODE_RPC_SCHEME://$NODE_RPC_ADDR" run "$@"
