#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2020 TQ Tezos <https://tqtezos.com/>
#
# SPDX-License-Identifier: LicenseRef-MIT-TQ

set -euo pipefail

# $PROTOCOL should be defined in the system unit environment
endorser="/usr/bin/tezos-endorser-$PROTOCOL"

endorser_dir="$DATA_DIR"

endorser_config="$endorser_dir/config"
mkdir -p "$endorser_dir"

if [ ! -f "$endorser_config" ]; then
    "$endorser" --base-dir "$endorser_dir" \
                --endpoint "$NODE_RPC_ENDPOINT" \
                config init --output "$endorser_config" >/dev/null 2>&1
else
    "$endorser" --base-dir "$endorser_dir" \
                --endpoint "$NODE_RPC_ENDPOINT" \
                config update >/dev/null 2>&1
fi

launch_endorser() {
    exec "$endorser" --base-dir "$endorser_dir" \
         --endpoint "$NODE_RPC_ENDPOINT" \
         run "$@"
}

if [[ -z "$ENDORSER_ACCOUNT" ]]; then
    launch_endorser "$@"
else
    launch_endorser "$ENDORSER_ACCOUNT" "$@"
fi
