#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2020 TQ Tezos <https://tqtezos.com/>
#
# SPDX-License-Identifier: LicenseRef-MIT-TQ

set -euo pipefail

# $PROTOCOL should be defined in the system unit environment
endorser="/usr/bin/tezos-endorser-$PROTOCOL"
tezos_client="/usr/bin/tezos-client"

endorser_dir="$DATA_DIR"

endorser_config="$endorser_dir/config"
mkdir -p "$endorser_dir"

if [ ! -f "$endorser_config" ]; then
    "$endorser" --base-dir "$endorser_dir" \
                --endpoint "$NODE_RPC_ENDPOINT" \
                config init --output "$endorser_config" >/dev/null 2>&1
else
    "$endorser" --base-dir "$endorser_dir" \
                --endpoint "$NODE_RPC_ENDPOINT" \
                config update >/dev/null 2>&1
fi

launch_endorser() {
    if [[ -n ${1-} ]]; then
        key_type="$("$tezos_client" show address "$BAKER_ADDRESS_ALIAS" -S | grep "Secret Key:" | cut -d':' -f2-2 | xargs)"
    fi
    if [[ ${key_type:-} == "encrypted" ]]; then
        password="$(systemd-ask-password --keyname="tezos-$BAKER_ADDRESS_ALIAS" --accept-cached \
            "Enter password for $BAKER_ADDRESS_ALIAS key:")"
        "$endorser" --base-dir "$endorser_dir" --endpoint "$NODE_RPC_ENDPOINT" \
             run "$@" <<< "$password" &
    else
        "$endorser" --base-dir "$endorser_dir" \
             --endpoint "$NODE_RPC_ENDPOINT" \
             run "$@" &
    fi
}

if [[ -z "$BAKER_ADDRESS_ALIAS" ]]; then
    launch_endorser "$@"
else
    launch_endorser "$BAKER_ADDRESS_ALIAS" "$@"
fi
