# SPDX-FileCopyrightText: 2020 TQ Tezos <https://tqtezos.com/>
#
# SPDX-License-Identifier: LicenseRef-MIT-TQ

FROM ubuntu:20.04
ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get update && apt-get install -y libev-dev libgmp-dev libhidapi-dev libffi-dev zlib1g-dev libpq-dev m4 perl pkg-config \
  debhelper dh-make dh-systemd devscripts autotools-dev python3 python3-distutils wget rsync
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:ubuntu-mozilla-security/rust-next -y && apt-get update && apt-get -y install cargo
RUN add-apt-repository ppa:avsm/ppa -y && apt-get update && apt-get -y install opam
ENV USER dockerbuilder
RUN useradd dockerbuilder && mkdir /tezos-packaging
ENV HOME /tezos-packaging
COPY meta.json /tezos-packaging/meta.json
COPY protocols.json /tezos-packaging/protocols.json
WORKDIR /tezos-packaging/docker
ENV OPAMROOT "/tezos-packaging/docker/opamroot"
COPY docker/package/*.py /tezos-packaging/docker/package/
COPY docker/package/defaults /tezos-packaging/docker/package/defaults
COPY docker/package/scripts /tezos-packaging/docker/package/scripts
COPY LICENSE /tezos-packaging/LICENSE
ENTRYPOINT ["python3", "-m", "package.package_generator"]
