# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

ARG dist
FROM ubuntu:focal AS srcs
RUN apt update -y
RUN apt install -y cargo-1.78 opam rsync python3

WORKDIR /sources

COPY meta.json meta.json
COPY docker/fetch_tezos_sources.py .
RUN python3 fetch_tezos_sources.py

COPY docker/vendor-rust-deps.py .
RUN python3 vendor-rust-deps.py

COPY docker/create_opam_repo.sh .
RUN ./create_opam_repo.sh

ARG dist
FROM ubuntu:${dist}

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update -y
RUN apt-get install -y libev-dev libgmp-dev libhidapi-dev libffi-dev \
                   zlib1g-dev libpq-dev m4 perl pkg-config \
                   debhelper dh-make dh-python devscripts autotools-dev \
                   python3-all python3-setuptools wget rsync cmake \
                   software-properties-common libprotobuf-dev libsqlite3-dev \
                   protobuf-compiler

ARG dist
RUN if [ "$dist" = "focal" ]; then apt-get install -y dh-systemd; fi

RUN install -m 0755 /usr/bin/python3 /usr/bin/builder

RUN apt-get -y install opam cargo cargo-1.78

ENV USER dockerbuilder
RUN useradd dockerbuilder

ENV HOME /tezos-packaging

WORKDIR /tezos-packaging/docker/sources

COPY --from=srcs /sources/tezos tezos
COPY --from=srcs /sources/opam-repository opam-repository

WORKDIR /tezos-packaging/docker
COPY meta.json /tezos-packaging/meta.json
COPY protocols.json /tezos-packaging/protocols.json
COPY docker/supported_versions.json /tezos-packaging/docker/supported_versions.json
COPY docker/package/*.py /tezos-packaging/docker/package/
COPY docker/package/defaults /tezos-packaging/docker/package/defaults
COPY docker/package/scripts /tezos-packaging/docker/package/scripts
COPY baking /tezos-packaging/docker/package/baking
# Uncomment once patches are needed once again
# COPY docker/package/patches /tezos-packaging/docker/package/patches
COPY LICENSE /tezos-packaging/LICENSE

ENTRYPOINT ["builder", "-m", "package.package_generator"]
