# SPDX-FileCopyrightText: 2021 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

FROM fedora:32
RUN dnf update -y
RUN dnf install -y libev-devel gmp-devel hidapi-devel libffi-devel zlib-devel libpq-devel m4 perl git pkg-config \
  rpmdevtools python3-devel python3-setuptools wget opam rsync which cargo autoconf
ENV USER dockerbuilder
RUN useradd dockerbuilder && mkdir /tezos-packaging
ENV HOME /tezos-packaging
COPY meta.json /tezos-packaging/meta.json
COPY protocols.json /tezos-packaging/protocols.json
WORKDIR /tezos-packaging/docker
ENV OPAMROOT "/tezos-packaging/docker/opamroot"
COPY docker/package/*.py /tezos-packaging/docker/package/
COPY docker/package/defaults /tezos-packaging/docker/package/defaults
COPY docker/package/scripts /tezos-packaging/docker/package/scripts
COPY LICENSE /tezos-packaging/LICENSE
ENTRYPOINT ["python3", "-m", "package.package_generator"]

