#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2022 Oxhead Alpha
# SPDX-License-Identifier: LicenseRef-MIT-OA

set -euo pipefail

tezos_client="/usr/bin/octez-client"

key_type="$("$tezos_client" show address "$BAKER_ADDRESS_ALIAS" -S | grep "Secret Key:" | cut -d':' -f2-2 | xargs)"

if [[ $key_type == "encrypted" ]]; then
    systemd-ask-password --keyname="tezos-$BAKER_ADDRESS_ALIAS" --no-output \
        "Enter password for $BAKER_ADDRESS_ALIAS key:"
fi
